<?php

namespace App\Admin\Controllers;

use App\Models\Master;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;

class MasterController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = '师傅管理';

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new Master);
        $grid->actions(function (Grid\Displayers\Actions $actions) {
            $actions->disableDelete();
            $actions->disableEdit();
        });
        $grid->disableCreateButton();
        $grid->column('id', 'ID');
        $grid->column('name', '用户名');
        $grid->column('real_name', '姓名');
        $grid->column('mobile', '手机');
        $grid->column('balance', '账户余额')->display(function ($value) {
            return number_format($value, 2);
        });
        $grid->column('offerOrders', '接单数')->display(function ($value) {
            return $value ? count($value) : 0;
        });

        $grid->column('runningOrders', '服务中的工单')->display(function ($value) {
            return $value ? count($value) : 0;
        });

        $grid->column('completedOrders', '完成的工单')->display(function ($value) {
            return $value ? count($value) : 0;
        });

        $grid->column('email', '邮箱');
        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(Master::findOrFail($id));
        return $show;
    }

    public function show($id, Content $content)
    {
        $master = Master::find($id);
        $offerOrders = $master->offerOrders;
        return $content
            ->title('师傅详细信息')
            ->view('admin.masters.show', [
                'master' => $master,
                'offerOrders' => $offerOrders
                ]); // TODO: Change the autogenerated stub
    }
}
