<?php

namespace App\Models;

use App\Models\Traits\AttributesTrait;
use App\Services\OrderStates\OrderState;
use App\Services\OrderStates\OrderStateInterface;
use App\Services\OrderStates\Paying;
use App\Services\OrderStates\Wait;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Order
 *
 * @property int $id
 * @property string $orderId 订单ID
 * @property int $type 订单类型
 * @property int $acceptedAmount 接单费用
 * @property int $additionAmount 额外费用
 * @property int $totalAmount 总费用
 * @property int $status 订单状态
 * @property int $contractorUserId 接单师傅用户ID
 * @property int $employerUserId 发单用户ID
 * @property \Illuminate\Support\Carbon|null $createdAt
 * @property \Illuminate\Support\Carbon|null $updatedAt
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereAcceptedAmount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereAdditionAmount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereContractorUserId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereEmployerUserId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereOrderId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereTotalAmount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Order whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Order extends Model
{
    use AttributesTrait;

    /**
     * @var OrderStateInterface $state
     * */
    protected $state = null;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::retrieved(function (Order $order) {
            switch ($order->status) {
                case OrderState::ORDER_WAIT: {
                    $order->setState(new Wait($order));
                    break;
                }
                case OrderState::ORDER_PAYING: {
                    $order->setState(new Paying($order));
                    break;
                }
                case OrderState::ORDER_PAID: {
                    break;
                }
                case OrderState::ORDER_COMPLETED: {
                    break;
                }
                case OrderState::ORDER_CANCEL: {
                    break;
                }
                case OrderState::ORDER_REFUNDING: {
                    break;
                }
                case OrderState::ORDER_REFUNDED: {
                    break;
                }
            }
        });
    }

    public function setState(OrderStateInterface $state)
    {
        $this->state = $state;
    }
}
